/home/jm/.local/lib/python3.10/site-packages/gymnax/environments/minatar/freeway.py:281: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in array is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  return jnp.array(cars, dtype=jnp.int_)
/home/jm/.local/lib/python3.10/site-packages/jax/_src/ops/scatter.py:96: FutureWarning: scatter inputs have incompatible types: cannot safely cast value from dtype=int32 to dtype=bool with jax_numpy_dtype_promotion='standard'. In future JAX releases this will result in an error.
  warnings.warn(
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/jm/workspace/jaxRL/ppo.py", line 330, in <module>
    main(args)
  File "/home/jm/workspace/jaxRL/ppo.py", line 306, in main
    out = train_jit(rng)
  File "/home/jm/workspace/jaxRL/ppo.py", line 274, in train
    runner_state, metric = jax.lax.scan(
  File "/home/jm/workspace/jaxRL/ppo.py", line 136, in _update_step
    runner_state, traj_batch = jax.lax.scan(
  File "/home/jm/workspace/jaxRL/ppo.py", line 127, in _env_step
    obsv, env_state, reward, done, info = jax.vmap(
  File "/home/jm/workspace/jaxRL/wrappers.py", line 95, in step
    obs, env_state, reward, done, info = self._env.step(
  File "/home/jm/workspace/jaxRL/wrappers.py", line 58, in step
    obs, state, reward, done, info = self._env.step(key, state, action, params)
  File "/home/jm/.local/lib/python3.10/site-packages/gymnax/environments/environment.py", line 45, in step
    obs_st, state_st, reward, done, info = self.step_env(key, state, action, params)
  File "/home/jm/.local/lib/python3.10/site-packages/gymnax/environments/minatar/freeway.py", line 82, in step_env
    state, reward, win_cond = step_agent(a, state, params)
  File "/home/jm/.local/lib/python3.10/site-packages/gymnax/environments/minatar/freeway.py", line 202, in step_agent
    return state.replace(pos=pos, move_timer=move_timer), reward, win_cond.item()
  File "/home/jm/.local/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 745, in meth
    return getattr(self.aval, name).fun(self, *args, **kwargs)
  File "/home/jm/.local/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 78, in _item
    arr = core.concrete_or_error(np.asarray, a, context="This occurred in the item() method of jax.Array")
jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape bool[].
This occurred in the item() method of jax.Array
The error occurred while tracing the function step at /home/jm/.local/lib/python3.10/site-packages/gymnax/environments/environment.py:32 for jit. This concrete value was not available in Python because it depends on the values of the arguments key.pos, key.move_timer, and state.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/jm/workspace/jaxRL/ppo.py", line 330, in <module>
    main(args)
  File "/home/jm/workspace/jaxRL/ppo.py", line 306, in main
    out = train_jit(rng)
  File "/home/jm/workspace/jaxRL/ppo.py", line 274, in train
    runner_state, metric = jax.lax.scan(
  File "/home/jm/workspace/jaxRL/ppo.py", line 136, in _update_step
    runner_state, traj_batch = jax.lax.scan(
  File "/home/jm/workspace/jaxRL/ppo.py", line 127, in _env_step
    obsv, env_state, reward, done, info = jax.vmap(
  File "/home/jm/workspace/jaxRL/wrappers.py", line 95, in step
    obs, env_state, reward, done, info = self._env.step(
  File "/home/jm/workspace/jaxRL/wrappers.py", line 58, in step
    obs, state, reward, done, info = self._env.step(key, state, action, params)
  File "/home/jm/.local/lib/python3.10/site-packages/gymnax/environments/environment.py", line 45, in step
    obs_st, state_st, reward, done, info = self.step_env(key, state, action, params)
  File "/home/jm/.local/lib/python3.10/site-packages/gymnax/environments/minatar/freeway.py", line 82, in step_env
    state, reward, win_cond = step_agent(a, state, params)
  File "/home/jm/.local/lib/python3.10/site-packages/gymnax/environments/minatar/freeway.py", line 202, in step_agent
    return state.replace(pos=pos, move_timer=move_timer), reward, win_cond.item()
  File "/home/jm/.local/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 745, in meth
    return getattr(self.aval, name).fun(self, *args, **kwargs)
  File "/home/jm/.local/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 78, in _item
    arr = core.concrete_or_error(np.asarray, a, context="This occurred in the item() method of jax.Array")
jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape bool[].
This occurred in the item() method of jax.Array
The error occurred while tracing the function step at /home/jm/.local/lib/python3.10/site-packages/gymnax/environments/environment.py:32 for jit. This concrete value was not available in Python because it depends on the values of the arguments key.pos, key.move_timer, and state.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError